version: 2.1

orbs:
  coveralls: coveralls/coveralls@2.2.5

workflows:
  run_tests:
    jobs:
      - lint_and_test

jobs:
  lint_and_test:
    docker:
      - image: cimg/ruby:3.4-node
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: false

      - run: if [ -e /var/run/docker.sock ]; then sudo chown circleci:circleci /var/run/docker.sock; fi

      - run:
          name: Build app
          command: make up

      - run:
          name: Run linter
          command: make lint

      - run:
          name: Run ruby tests
          command: |
            bundle exec rspec spec
