version: 2.1

workflows:
  version: 2
  run_tests:
    jobs:
      - run_tests

jobs:
  run_tests:
    docker:
      - image: cimg/ruby:3.4-node
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout

      - run:
          name: make sure we have the latest bundler
          command: |
            sudo gem update --system
            gem install -f bundler:2.1.4

      - run:
          name: Build app
          command: make up

      - run:
          name: Run linter
          command: make lint

      - run:
          name: Run rubocop
          command: bundle exec rubocop

      - run:
          name: Run ruby tests
          command: |
            bundle exec rspec spec
